//===- LVXComposites.h - The composite ops and their parts -------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// The 256-bit operations the ISA has no instruction for, generated by lvx-mds'
// `MDS/BE/MLIR` from `Builtin@split` into `LVXComposites.inc`: each is the
// named 128-bit instruction on each pair of its quad operands, issued in one
// bundle. In a bundle every read precedes every write, so the two parts
// together are one operation whose result may overlap its operands -- which
// is why the dialect has one op for them, typed over the quad, and why the
// assembly printer prints the parts with a single `;;` after them
// (lvx-mlir/docs/Bundling.md §5).
//
//===----------------------------------------------------------------------===//

#ifndef MLIR_DIALECT_LVX_IR_LVXCOMPOSITES_H
#define MLIR_DIALECT_LVX_IR_LVXCOMPOSITES_H

#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"

#include <optional>

#include "mlir/Dialect/LVX/IR/LVXComposites.inc"

#endif // MLIR_DIALECT_LVX_IR_LVXCOMPOSITES_H
